---
title: "Package Vignette"
output: html_document
---

#Data Format
*The dataset must have information on year and specific state. The state variable must be called "state_full" and have the full name for the state in all lower case letters. Some data cleaning may be needed for the function to run properly. 

#Mapping National Prevalence 
Function: map_national_prevalence(data,existing_cases,population, state, year)
##Arguments: 
data: dataset of choice formatted as specified
existing cases: variable for prevalence calculation 
population: variable for population estimate
state: state arugment must be "state_full"
year: year argument must be "year"

*Example code: 
map_national_prevalence(Fatalities_clean,existing_cases= "fatal",population="pop", state="state", year="year")

#Mapping Regional Prevalence
##For user convenience, this package uses regional functions to map prevalence. The regions are: Northeast, South, Midwest and West. 
*Include inforamtion on what states are included in each dataset

Function: map_northeast_prevalence(data,existing_cases,population, state, year)
###Arguments: 
data: dataset of choice formatted as specified
existing cases: variable for prevalence calculation 
population: variable for population estimate
state: state arugment must be "state_full"
year: year argument must be "year"

#Visualizing Data through plots
##1. Must have cleaned data with no NAs (Reference link: https://stackoverflow.com/questions/4862178/remove-rows-with-all-or-some-nas-missing-values-in-data-frame )
##2. Epiplot function arguments: (data, x, y, graph, fill, title, xlab, ylab, legend)
##3. Graphs: bar plot ("bar"), grouped bar plot ("bargroup"), stacked bar plot ("barstack"), box plot ("boxplot"), box plot with correlating dots ("dotboxplot"), histogram ("hist"), density plot ("densityhist"), scatter plot ("scatter"), scatter plot with correlating line ("scatterline"), linear regression ("linreg").
##4. Input the correct arguments:
###bar plot: (data=data, x=data$x, graph="bar", title="Title of plot", xlab="x-axis label", ylab= "y-axis label")
###grouped bar plot: (data=data, x=data$x,y=data$y, graph="bargroup",fill=data$fill, title="Title of plot", xlab="x-axis labellab",  ylab="y-axis label")
###stacked bar plot: (data=data, x=data$x,y=data$y, graph="barstack",fill=data$fill, title="Title of plot", xlab="x-axis labellab",  ylab="y-axis label")
###box plot: (data=data, x=data$x,y=data$y, graph="boxplot", title="Title of plot", xlab="x-axis label",  ylab="y-axis label")
###box plot with correlating dots:(data=data,y=data$y, graph="dotboxplot", title="Title of plot", xlab="x-axis labellab",  ylab="y-axis label")
###histogram: (data=data, x=data$x, graph="hist", title="Title of plot", xlab="x-axis label",  ylab="y-axis label")
###density plot: (data=data, x=data$x, graph="densityhist", title="Title of plot", xlab="x-axis label",  ylab="y-axis label")
###scatter plot: (data=data, x=data$x, y=data$y, graph="scatter",fill=data$fill, title="Title of plot", xlab="x-axis label",  ylab="y-axis label", legend="Title of legend fill")
###scatter plot with correlating line: (data=data, x=data$x, y=data$y, graph="scatterline",fill=data$fill, title="Title of plot", xlab="x-axis label",  ylab="y-axis label", legend="Title of legend fill")
###linear regression: (data=data, x=data$x, y=data$y, graph="linreg",fill=data$fill, title="Title of plot", xlab="x-axis label",  ylab="y-axis label", legend="Title of legend fill")